name: 3dunet

channels:
  - conda-forge
  - pytorch

dependencies:
  - python 3.8
  - pytorch
  - torchvision
  - tensorboardx
  - h5py
  - scipy
  - scikit-image
  - scikit-learn
  - pyyaml
  - hdbscan
  - pytest
  - matplotlib
