name: 3dunet

channels:
  - pytorch
  - conda-forge

dependencies:
  - python 3.8
  - pytorch
  - tensorboard
  # workaround the issue https://github.com/pytorch/pytorch/pull/69904
  - setuptools 59.5.0
  - h5py
  - scipy
  - scikit-image
  - scikit-learn
  - pyyaml
  - pytest
  - matplotlib
