manual_seed: 0
model:
  name: UNet2D
  in_channels: 1
  out_channels: 1
  layer_order: gcr
  f_maps: 32
  num_groups: 8
  final_sigmoid: true
  is_segmentation: true
trainer:
  checkpoint_dir: 3dunet-dsb
  resume: null
  validate_after_iters: 20
  log_after_iters: 20
  epochs: 100
  iters: 100000
  eval_score_higher_is_better: True
optimizer:
  learning_rate: 0.0002
  weight_decay: 0.00001
loss:
  name: BCEDiceLoss
  skip_last_target: true
eval_metric:
  name: BlobsAveragePrecision
  threshold: 0.4
  use_last_target: true
lr_scheduler:
  name: ReduceLROnPlateau
  mode: max
  factor: 0.5
  patience: 100
loaders:
  dataset: DSB2018Dataset
  batch_size: 4
  num_workers: 4
  train:
    file_paths:
      - '/home/adrian/workspace/ilastik-datasets/dsb2018/train'

    transformer:
      raw:
        - name: CropToFixed
          size: [256, 256]
        - name: Standardize
        - name: RandomFlip
        - name: RandomRotate90
        - name: RandomRotate
          axes: [[2, 1]]
          angle_spectrum: 30
          mode: reflect
        - name: ElasticDeformation
          spline_order: 3
          execution_probability: 0.2
        - name: AdditiveGaussianNoise
          execution_probability: 0.2
        - name: AdditivePoissonNoise
          execution_probability: 0.2
        - name: ToTensor
          expand_dims: true
      label:
        - name: CropToFixed
          size: [256, 256]
        - name: RandomFlip
        - name: RandomRotate90
        - name: RandomRotate
          axes: [[2, 1]]
          angle_spectrum: 30
          mode: reflect
        - name: ElasticDeformation
          spline_order: 0
          execution_probability: 0.2
        - name: Relabel
        - name: BlobsToMask
          append_label: true
        - name: ToTensor
          expand_dims: true
  val:
    file_paths:
      - '/home/adrian/workspace/ilastik-datasets/dsb2018/test'

    transformer:
      raw:
        - name: CropToFixed
          size: [256, 256]
        - name: Standardize
        - name: ToTensor
          expand_dims: true
      label:
        - name: CropToFixed
          size: [256, 256]
        - name: Relabel
        - name: BlobsToMask
          append_label: true
        - name: ToTensor
          expand_dims: true